import type { AlgorithmInfo } from '@/types'

export const algorithmInfo: Record<string, AlgorithmInfo> = {
  bubble: {
    name: 'Bubble Sort',
    description: 'Algoritmo de ordenação por comparações adjacentes',
    dataStructure: 'Array',
    dataStructureExplanation: 'Utiliza apenas o array original, realizando trocas in-place. Não necessita de estruturas auxiliares, operando diretamente sobre os elementos adjacentes do array.',
    explanation: 'O Bubble Sort funciona comparando elementos adjacentes e trocando-os se estiverem na ordem errada. O processo se repete até que nenhuma troca seja necessária, indicando que o array está ordenado. A cada passagem, o maior elemento "flutua" para sua posição final, como bolhas subindo na água.',
    bestCase: 'O(n)',
    averageCase: 'O(n²)',
    worstCase: 'O(n²)',
    space: 'O(1)',
    complexityJustification: 'No melhor caso (array já ordenado), apenas uma passagem é necessária: O(n). No caso médio e pior (array invertido), são necessárias n-1 passagens com n-i comparações cada, resultando em O(n²). Espaço O(1) pois opera in-place.',
    pseudocode: [
      'procedure bubbleSort(A: array)',
      '    n = length(A)',
      '    for i = 0 to n-1 do',
      '        swapped = false',
      '        for j = 0 to n-i-2 do',
      '            if A[j] > A[j+1] then',
      '                swap(A[j], A[j+1])',
      '                swapped = true',
      '            end if',
      '        end for',
      '        if not swapped then break',
      '    end for',
      'end procedure'
    ]
  },
  selection: {
    name: 'Selection Sort',
    description: 'Algoritmo de ordenação por seleção do mínimo',
    dataStructure: 'Array',
    dataStructureExplanation: 'Opera diretamente sobre o array original, dividindo-o logicamente em duas partes: a parte ordenada (à esquerda) e a parte não ordenada (à direita). Não requer memória auxiliar.',
    explanation: 'O Selection Sort divide o array em duas partes: ordenada e não ordenada. A cada iteração, encontra o menor elemento na parte não ordenada e o move para o final da parte ordenada. O algoritmo sempre faz o mesmo número de comparações, independente da ordem inicial.',
    bestCase: 'O(n²)',
    averageCase: 'O(n²)',
    worstCase: 'O(n²)',
    space: 'O(1)',
    complexityJustification: 'Sempre realiza (n-1) + (n-2) + ... + 1 = n(n-1)/2 comparações, resultando em O(n²) em todos os casos. No entanto, faz no máximo O(n) trocas, sendo eficiente quando o custo de troca é alto. Espaço O(1) pois opera in-place.',
    pseudocode: [
      'procedure selectionSort(A: array)',
      '    n = length(A)',
      '    for i = 0 to n-1 do',
      '        minIdx = i',
      '        for j = i+1 to n-1 do',
      '            if A[j] < A[minIdx] then',
      '                minIdx = j',
      '            end if',
      '        end for',
      '        if minIdx != i then',
      '            swap(A[i], A[minIdx])',
      '        end if',
      '    end for',
      'end procedure'
    ]
  },
  insertion: {
    name: 'Insertion Sort',
    description: 'Algoritmo de ordenação por inserção',
    dataStructure: 'Array',
    dataStructureExplanation: 'Mantém uma sub-lista ordenada no início do array, inserindo elementos um a um na posição correta. Opera in-place, deslocando elementos para abrir espaço para inserção.',
    explanation: 'O Insertion Sort constrói a lista ordenada um elemento por vez. Para cada elemento, ele é comparado com os anteriores e inserido na posição correta. É similar a como organizamos cartas na mão: pegamos uma carta e a inserimos no lugar certo entre as já organizadas.',
    bestCase: 'O(n)',
    averageCase: 'O(n²)',
    worstCase: 'O(n²)',
    space: 'O(1)',
    complexityJustification: 'No melhor caso (array ordenado), cada elemento requer apenas uma comparação: O(n). No pior caso (array invertido), cada elemento é comparado com todos os anteriores: 1+2+...+(n-1) = O(n²). É eficiente para arrays pequenos ou quase ordenados.',
    pseudocode: [
      'procedure insertionSort(A: array)',
      '    n = length(A)',
      '    for i = 1 to n-1 do',
      '        key = A[i]',
      '        j = i - 1',
      '        while j >= 0 and A[j] > key do',
      '            A[j+1] = A[j]',
      '            j = j - 1',
      '        end while',
      '        A[j+1] = key',
      '    end for',
      'end procedure'
    ]
  },
  merge: {
    name: 'Merge Sort',
    description: 'Algoritmo de ordenação por divisão e conquista',
    dataStructure: 'Array + Arrays Auxiliares',
    dataStructureExplanation: 'Utiliza a técnica de divisão e conquista, dividindo o array em sub-arrays menores. Requer arrays auxiliares para a fase de merge, onde os sub-arrays ordenados são combinados. A estrutura de chamadas recursivas forma uma árvore binária.',
    explanation: 'O Merge Sort usa a estratégia de "dividir e conquistar". Divide o array pela metade recursivamente até ter sub-arrays de um elemento (que são naturalmente ordenados). Então, combina (merge) os sub-arrays de forma ordenada. A operação de merge é a chave: compara elementos dos dois sub-arrays e os coloca em ordem no array resultante.',
    bestCase: 'O(n log n)',
    averageCase: 'O(n log n)',
    worstCase: 'O(n log n)',
    space: 'O(n)',
    complexityJustification: 'A divisão cria log₂(n) níveis de recursão. Em cada nível, o merge processa todos os n elementos. Portanto: O(n × log n) em todos os casos. Espaço O(n) devido ao array auxiliar necessário para o merge. É estável e previsível.',
    pseudocode: [
      'procedure mergeSort(A: array, left, right)',
      '    if left < right then',
      '        mid = (left + right) / 2',
      '        mergeSort(A, left, mid)',
      '        mergeSort(A, mid+1, right)',
      '        merge(A, left, mid, right)',
      '    end if',
      '',
      'procedure merge(A, left, mid, right)',
      '    create temp arrays L and R',
      '    copy A[left..mid] to L',
      '    copy A[mid+1..right] to R',
      '    i = 0, j = 0, k = left',
      '    while i < len(L) and j < len(R)',
      '        if L[i] <= R[j] then',
      '            A[k] = L[i]; i++',
      '        else',
      '            A[k] = R[j]; j++',
      '        k++',
      '    copy remaining elements'
    ]
  },
  quick: {
    name: 'Quick Sort',
    description: 'Algoritmo de ordenação por particionamento',
    dataStructure: 'Array + Pilha de Recursão',
    dataStructureExplanation: 'Utiliza o array original para ordenação in-place e uma pilha implícita (através da recursão) para gerenciar as partições. O pivô divide o array em elementos menores (esquerda) e maiores (direita).',
    explanation: 'O Quick Sort seleciona um elemento como "pivô" e particiona o array: elementos menores vão para a esquerda, maiores para a direita. O processo se repete recursivamente em cada partição. A escolha do pivô afeta drasticamente o desempenho. Estratégias comuns incluem usar o último elemento, o primeiro, ou a mediana de três.',
    bestCase: 'O(n log n)',
    averageCase: 'O(n log n)',
    worstCase: 'O(n²)',
    space: 'O(log n)',
    complexityJustification: 'No melhor/médio caso, o pivô divide o array aproximadamente ao meio, criando log₂(n) níveis com n operações cada: O(n log n). No pior caso (pivô sempre é o menor ou maior), cria n níveis: O(n²). Espaço O(log n) para a pilha de recursão.',
    pseudocode: [
      'procedure quickSort(A: array, low, high)',
      '    if low < high then',
      '        pi = partition(A, low, high)',
      '        quickSort(A, low, pi - 1)',
      '        quickSort(A, pi + 1, high)',
      '    end if',
      '',
      'procedure partition(A, low, high)',
      '    pivot = A[high]',
      '    i = low - 1',
      '    for j = low to high - 1 do',
      '        if A[j] < pivot then',
      '            i = i + 1',
      '            swap(A[i], A[j])',
      '        end if',
      '    end for',
      '    swap(A[i + 1], A[high])',
      '    return i + 1'
    ]
  },
  heap: {
    name: 'Heap Sort',
    description: 'Algoritmo de ordenação usando heap binária',
    dataStructure: 'Array como Heap Binária (Max-Heap)',
    dataStructureExplanation: 'Representa uma árvore binária completa usando um array. Para o índice i: filho esquerdo = 2i+1, filho direito = 2i+2, pai = (i-1)/2. A propriedade de max-heap garante que cada pai é maior que seus filhos.',
    explanation: 'O Heap Sort utiliza uma estrutura de dados chamada heap binária (max-heap). Primeiro, constrói um max-heap onde cada pai é maior que seus filhos. O maior elemento (raiz) é movido para o final do array. O processo de "heapify" restaura a propriedade de heap e se repete até ordenar todo o array.',
    bestCase: 'O(n log n)',
    averageCase: 'O(n log n)',
    worstCase: 'O(n log n)',
    space: 'O(1)',
    complexityJustification: 'Construir o heap custa O(n). Extrair cada um dos n elementos e fazer heapify (O(log n) cada) resulta em O(n log n). Total: O(n log n) em todos os casos. Espaço O(1) pois usa o próprio array como heap, ordenando in-place.',
    pseudocode: [
      'procedure heapSort(A: array)',
      '    n = length(A)',
      '    // Build max heap',
      '    for i = n/2 - 1 downto 0 do',
      '        heapify(A, n, i)',
      '    end for',
      '    // Extract elements',
      '    for i = n - 1 downto 1 do',
      '        swap(A[0], A[i])',
      '        heapify(A, i, 0)',
      '    end for',
      '',
      'procedure heapify(A, n, i)',
      '    largest = i',
      '    left = 2*i + 1',
      '    right = 2*i + 2',
      '    if left < n and A[left] > A[largest]',
      '        largest = left',
      '    if right < n and A[right] > A[largest]',
      '        largest = right',
      '    if largest != i then',
      '        swap(A[i], A[largest])',
      '        heapify(A, n, largest)'
    ]
  }
}
